Merge several fixes and cleanup
neicnordic/ega-data-api pull request #10
Opened 2019-10-02 12:38 UTC by amgadhanafy

### Describe the pull request:

- [x] Bug fix
- [x] Code cleanup

### Pull request long description:

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2019-10-02 13:12 UTC, dtitov approved these changes

2019-10-03 11:42 UTC, blankdots requested changes
two files was previously removed, we should keep it like that.
We might want to review the log messages , as they are not really that informative to be relevant in any production environment, e.g.:
>  log.info("NO!!");

Will start an issue on that.

2019-10-03 11:42 UTC, blankdots commented on ega-data-api-filedatabase/src/main/java/eu/elixir/ega/ebi/downloader/service/internal/LocalEGAFileServiceImpl.java
> +
this should not be here, it was removed in: https://github.com/neicnordic/ega-data-api/pull/3

2019-10-03 11:42 UTC, blankdots commented on extras/travis_push_docker_hub.sh
> +
was removed in: https://github.com/neicnordic/ega-data-api/pull/2

2019-10-03 11:49 UTC, blankdots commented
Follow up issue created: https://github.com/neicnordic/ega-data-api/issues/11

2019-10-03 12:08 UTC, blankdots approved these changes

2019-10-03 12:25 UTC, merged